### ISSUE TITLE
Cant create static Proxy Group

### ISSUE THREAD

**Issue by Juulsn** [TimoCloud/TimoCloud-5#5]
[2018-02-25 11:02:28] [SEVERE ] Error while saving proxy groups:  
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 411 path $[0].serverGroups[8]
        at com.google.gson.internal.Streams.parse(Streams.java:58)
        at com.google.gson.JsonParser.parse(JsonParser.java:84)
        at com.google.gson.JsonParser.parse(JsonParser.java:59)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at cloud.timo.TimoCloud.core.managers.CoreFileManager.saveJson(CoreFileManager.java:111)
        at cloud.timo.TimoCloud.core.managers.CoreServerManager.saveProxyGroups(CoreServerManager.java:104)
        at cloud.timo.TimoCloud.core.managers.CommandManager.onCommand(CommandManager.java:217)
        at cloud.timo.TimoCloud.core.managers.CommandManager.onCommand(CommandManager.java:40)
        at cloud.timo.TimoCloud.core.managers.CommandManager.onCommand(CommandManager.java:32)
        at cloud.timo.TimoCloud.core.TimoCloudCore.waitForCommands(TimoCloudCore.java:158)
        at cloud.timo.TimoCloud.core.TimoCloudCore.load(TimoCloudCore.java:100)
        at cloud.timo.TimoCloud.ModuleLoader.loadModule(ModuleLoader.java:135)
        at cloud.timo.TimoCloud.ModuleLoader.main(ModuleLoader.java:53)
Caused by: java.io.EOFException: End of input at line 1 column 411 path $[0].serverGroups[8]
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:467)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:713)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:697)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 12 more

I used this command:

addgroup proxy Proxy 2048 true BASE-1

**Comment by TimoZikeli** [comment]
Not reproducible in #v5.0.5.
