### ISSUE TITLE
NoSuchFieldError: LEGACY_WALL_SIGN

### ISSUE THREAD

**Issue by LucHeart** [TimoCloud/TimoCloud-5#67]
I noticed that TimoCloud thows an Exception on PlayerInteractEvent (Spigot Plugin).
If I rightclick anything in the world, I get this.

```
[20:51:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to TimoCloud v5.5.0
java.lang.NoSuchFieldError: LEGACY_WALL_SIGN
	at cloud.timo.TimoCloud.bukkit.listeners.PlayerInteract.onPlayerInteractEvent(PlayerInteract.java:25) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:486) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[20:51:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to TimoCloud v5.5.0
java.lang.NoSuchFieldError: LEGACY_WALL_SIGN
	at cloud.timo.TimoCloud.bukkit.listeners.PlayerInteract.onPlayerInteractEvent(PlayerInteract.java:25) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[spigot.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:486) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]


```

**Comment by LucHeart** [comment]
6.0 - Fixed
